// Typed theme token system — Twenty CRM style
// Usage: import { theme } from "@/styles/tokens/theme"
// Then: style={{ background: theme.bg.panel, color: theme.font.primary }}

export const theme = {
  bg: {
    outer: "var(--admin-bg-outer)",
    panel: "var(--admin-bg-panel)",
    card: "var(--admin-bg-card)",
    cardHover: "var(--admin-bg-card-hover)",
    input: "var(--admin-bg-input)",
    overlay: "var(--admin-bg-overlay)",
    hover: "var(--admin-bg-hover)",
    active: "var(--admin-bg-active)",
    iconBox: "var(--admin-bg-icon-box)",
  },
  font: {
    primary: "var(--admin-font-primary)",
    secondary: "var(--admin-font-secondary)",
    tertiary: "var(--admin-font-tertiary)",
    light: "var(--admin-font-light)",
    sectionLabel: "var(--admin-font-section-label)",
    family: "var(--admin-font-family)",
  },
  border: {
    default: "var(--admin-border-default)",
    hover: "var(--admin-border-hover)",
    light: "var(--admin-border-light)",
    panel: "var(--admin-border-panel)",
  },
  accent: {
    green: "var(--admin-accent-green)",
    red: "var(--admin-accent-red)",
    blue: "var(--admin-accent-blue)",
    purple: "var(--admin-accent-purple)",
    amber: "var(--admin-accent-amber)",
    orange: "var(--admin-accent-orange)",
  },
  accentBg: {
    green: "var(--admin-accent-bg-green)",
    red: "var(--admin-accent-bg-red)",
    blue: "var(--admin-accent-bg-blue)",
    purple: "var(--admin-accent-bg-purple)",
    amber: "var(--admin-accent-bg-amber)",
    orange: "var(--admin-accent-bg-orange)",
  },
  accentBorder: {
    green: "var(--admin-accent-border-green)",
    red: "var(--admin-accent-border-red)",
    blue: "var(--admin-accent-border-blue)",
    purple: "var(--admin-accent-border-purple)",
    amber: "var(--admin-accent-border-amber)",
    orange: "var(--admin-accent-border-orange)",
  },
  animation: {
    instant: "75ms",
    fast: "150ms",
    normal: "300ms",
    slow: "1.5s",
  },
  spacing: {
    0: "0px",
    0.5: "2px",
    1: "4px",
    2: "8px",
    3: "12px",
    4: "16px",
    5: "20px",
    6: "24px",
    8: "32px",
    10: "40px",
    12: "48px",
  },
  radius: {
    sm: "4px",
    md: "6px",
    lg: "8px",
    xl: "12px",
  },
  shadow: {
    light: "0 1px 3px rgba(0,0,0,0.08)",
    strong: "0 4px 12px rgba(0,0,0,0.12)",
    superHeavy: "0 24px 48px rgba(0,0,0,0.4)",
  },
  fontSize: {
    xs: "10px",
    sm: "11px",
    base: "13px",
    md: "14px",
    lg: "16px",
    xl: "20px",
    "2xl": "24px",
  },
} as const;
