export const actionCards = [
  {
    id: 1,
    title: "dashboard.startAssessment",
    subtitle: "dashboard.completeEvaluations",
    icon: "🧠",
    action: "dashboard.beginAssessment",
    link: "/dashboard/assessments",
    variant: "primary",
    badge: "dashboard.recommended",
  },
  {
    id: 2,
    title: "dashboard.startCourse",
    subtitle: "dashboard.goToCatalog",
    icon: "📚",
    action: "dashboard.browseCourses",
    link: "/dashboard/learning/courses",
    variant: "secondary",
  },
  {
    id: 3,
    title: "dashboard.buildResume",
    subtitle: "dashboard.createWithAI",
    icon: "📄",
    action: "dashboard.startBuilding",
    link: "/dashboard/resumes",
    variant: "secondary",
    badge: "dashboard.withAI",
  },
  {
    id: 4,
    title: "dashboard.scheduleCoaching",
    subtitle: "dashboard.bookSession",
    icon: "👥",
    action: "dashboard.bookSession",
    link: "/dashboard/book-coach",
    variant: "secondary",
  },
];
