-- services/api/tests/FormMaps.IntegrationTests/Billing/Payouts/Data/coach-payouts-schema.sql
--
-- DDL for the audit D3 monthly coach payout harness (CoachPayoutRepository). Column sets are the production ones
-- (api/prisma/schema.prisma models Coach, Booking, Payment, Payout, AuditLog) for every column the queries touch,
-- plus every column the vendored policies reference.
--
--   payments, payouts -> policied in production (TestSupport/Rls/007-self-scoped.sql): payments owner-only,
--       payouts via coaches.userId. Named in CoachPayoutDatabaseFixture.PoliciedTables.
--   coaches, bookings, audit_logs -> UNPOLICIED in production (007's escalated list / 005's unpolicied list).
--
-- "updatedAt" is Prisma @updatedAt: NOT NULL with NO database default — every writer must bind it.
-- "id" is Prisma @default(uuid()), generated by the client: no database default either.

CREATE TYPE "BookingStatus" AS ENUM ('pending', 'confirmed', 'completed', 'cancelled', 'rescheduled');
CREATE TYPE "PayoutStatus" AS ENUM ('pending', 'approved', 'processing', 'completed', 'rejected', 'failed');

CREATE TABLE "coaches" (
  "id" text PRIMARY KEY,
  "userId" text NOT NULL UNIQUE,
  "email" text NOT NULL,
  "name" text NOT NULL,
  "platformCommission" decimal(65,30) NOT NULL DEFAULT 0,
  "isActive" boolean NOT NULL DEFAULT true,
  "createdDate" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp(3) NOT NULL
);

CREATE TABLE "bookings" (
  "id" text PRIMARY KEY,
  "coachId" text NOT NULL REFERENCES "coaches"("id"),
  "studentId" text NOT NULL,
  "startTime" timestamp(3) NOT NULL,
  "endTime" timestamp(3) NOT NULL,
  "status" "BookingStatus" NOT NULL DEFAULT 'pending',
  "completedAt" timestamp(3),
  "amount" bigint,
  "currency" text,
  "isPaymentDone" boolean NOT NULL DEFAULT false,
  "paidAt" timestamp(3),
  "isActive" boolean NOT NULL DEFAULT true,
  "createdDate" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp(3) NOT NULL
);

CREATE TABLE "payments" (
  "id" text PRIMARY KEY,
  "userId" text NOT NULL,
  "amount" decimal(65,30) NOT NULL DEFAULT 0,
  "currency" text NOT NULL DEFAULT 'usd',
  "status" text NOT NULL,
  "paymentIntentId" text NOT NULL DEFAULT '',
  "bookingId" text,
  "isActive" boolean NOT NULL DEFAULT true,
  "createdDate" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp(3) NOT NULL
);

CREATE TABLE "payouts" (
  "id" text PRIMARY KEY,
  "coachId" text NOT NULL REFERENCES "coaches"("id"),
  "amount" decimal(65,30) NOT NULL,
  "currency" text NOT NULL DEFAULT 'USD',
  "status" "PayoutStatus" NOT NULL DEFAULT 'pending',
  "requestedAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "processedAt" timestamp(3),
  "transactionId" text,
  "notes" text,
  "failureReason" text,
  "periodStart" timestamp(3),
  "periodEnd" timestamp(3),
  "approvedBy" text,
  "approvedAt" timestamp(3),
  "rejectedBy" text,
  "rejectedAt" timestamp(3),
  "rejectionReason" text,
  "platformFeeAmount" decimal(65,30),
  "platformFeePercentage" decimal(65,30),
  "netAmount" decimal(65,30),
  "isActive" boolean NOT NULL DEFAULT true,
  "createdBy" text,
  "createdDate" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedBy" text,
  "updatedAt" timestamp(3) NOT NULL
);

-- model AuditLog — the legacy trail both backends write. Unpolicied.
CREATE TABLE "audit_logs" (
  "id" text PRIMARY KEY,
  "actorId" text NOT NULL,
  "actorEmail" text NOT NULL,
  "action" text NOT NULL,
  "resourceType" text NOT NULL,
  "resourceId" text,
  "details" jsonb,
  "ipAddress" text,
  "isActive" boolean NOT NULL DEFAULT true,
  "createdDate" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp(3) NOT NULL
);
