// Role constants — must match backend Authorization/Roles.cs
export const Roles = {
  SUPER_ADMIN: "Super Admin",
  SCHOOL_ADMIN: "school_admin",
  COUNSELOR: "counselor",
  TEACHER: "teacher",
  STUDENT: "student",
  COACH: "coach",
  PARENT: "parent",
} as const;

export type RoleName = (typeof Roles)[keyof typeof Roles];

// Permission constants — must match backend Authorization/Permissions.cs
export const Permissions = {
  Admin: {
    Dashboard: "admin:dashboard",
    Users: "admin:users",
    Schools: "admin:schools",
    Roles: "admin:roles",
    Plans: "admin:plans",
    Payouts: "admin:payouts",
    Coaches: "admin:coaches",
  },
  School: {
    Manage: "school:manage",
    Users: "school:users",
    Billing: "school:billing",
    Integrations: "school:integrations",
    DataMapping: "school:data-mapping",
  },
  Students: {
    Read: "students:read",
    Write: "students:write",
    Import: "students:import",
  },
  Courses: {
    Read: "courses:read",
    Write: "courses:write",
  },
  CoursePlans: {
    Read: "course-plans:read",
    Write: "course-plans:write",
    Approve: "course-plans:approve",
  },
  Grades: {
    Read: "grades:read",
    Import: "grades:import",
  },
  Assessments: {
    Take: "assessments:take",
    Read: "assessments:read",
  },
  Evaluations: {
    Read: "evaluations:read",
    Submit: "evaluations:submit",
    Manage: "evaluations:manage",
  },
  Reports: {
    Read: "reports:read",
    School: "reports:school",
  },
  Alerts: {
    Read: "alerts:read",
    Manage: "alerts:manage",
  },
  Counselor: {
    Dashboard: "counselor:dashboard",
    Notes: "counselor:notes",
    Sessions: "counselor:sessions",
    SessionRequest: "counselor:session-request",
  },
  Coaching: {
    Dashboard: "coaching:dashboard",
    Sessions: "coaching:sessions",
    Book: "coaching:book",
    Earnings: "coaching:earnings",
    Profile: "coaching:profile",
  },
  Parent: {
    Dashboard: "parent:dashboard",
    Children: "parent:children",
  },
  Teacher: {
    Dashboard: "teacher:dashboard",
  },
  Recommendations: {
    Respond: "recommendations:respond",
  },
  Careers: { Read: "careers:read" },
  Universities: { Read: "universities:read" },
  Resume: { Manage: "resume:manage" },
  Portfolio: { Manage: "portfolio:manage" },
  Learning: { Access: "learning:access" },
  Profile: { Read: "profile:read", Write: "profile:write" },
  Subscriptions: { Read: "subscriptions:read", Manage: "subscriptions:manage" },
} as const;

// Role → Permissions map (mirrors backend RolePermissionMap.cs)
export const RolePermissionMap: Record<string, string[]> = {
  super_admin: [
    Permissions.Admin.Dashboard, Permissions.Admin.Users, Permissions.Admin.Schools,
    Permissions.Admin.Roles, Permissions.Admin.Plans, Permissions.Admin.Payouts, Permissions.Admin.Coaches,
    Permissions.School.Manage, Permissions.School.Users, Permissions.School.Billing,
    Permissions.School.Integrations, Permissions.School.DataMapping,
    Permissions.Students.Read, Permissions.Students.Write, Permissions.Students.Import,
    Permissions.Courses.Read, Permissions.Courses.Write,
    Permissions.CoursePlans.Read, Permissions.CoursePlans.Write,
    Permissions.Grades.Read, Permissions.Grades.Import,
    Permissions.Assessments.Read,
    Permissions.Evaluations.Read, Permissions.Evaluations.Manage,
    Permissions.Reports.Read, Permissions.Reports.School,
    Permissions.Alerts.Read, Permissions.Alerts.Manage,
    Permissions.Careers.Read, Permissions.Universities.Read,
    Permissions.Profile.Read, Permissions.Profile.Write,
    Permissions.Subscriptions.Read, Permissions.Subscriptions.Manage,
  ],
  school_admin: [
    Permissions.School.Manage, Permissions.School.Users, Permissions.School.Billing,
    Permissions.School.Integrations, Permissions.School.DataMapping,
    Permissions.Students.Read, Permissions.Students.Write, Permissions.Students.Import,
    Permissions.Courses.Read, Permissions.Courses.Write,
    Permissions.CoursePlans.Read, Permissions.CoursePlans.Write, Permissions.CoursePlans.Approve,
    Permissions.Grades.Read, Permissions.Grades.Import,
    Permissions.Assessments.Read,
    Permissions.Evaluations.Read, Permissions.Evaluations.Manage,
    Permissions.Reports.Read, Permissions.Reports.School,
    Permissions.Alerts.Read, Permissions.Alerts.Manage,
    Permissions.Careers.Read, Permissions.Universities.Read,
    Permissions.Profile.Read, Permissions.Profile.Write,
    Permissions.Subscriptions.Read,
  ],
  counselor: [
    Permissions.Students.Read,
    Permissions.Courses.Read,
    Permissions.CoursePlans.Read, Permissions.CoursePlans.Write, Permissions.CoursePlans.Approve,
    Permissions.Grades.Read,
    Permissions.Assessments.Read,
    Permissions.Evaluations.Read, Permissions.Evaluations.Submit,
    Permissions.Reports.Read,
    Permissions.Alerts.Read, Permissions.Alerts.Manage,
    Permissions.Counselor.Dashboard, Permissions.Counselor.Notes, Permissions.Counselor.Sessions,
    Permissions.Careers.Read, Permissions.Universities.Read,
    Permissions.Profile.Read, Permissions.Profile.Write,
  ],
  teacher: [
    Permissions.Students.Read,
    Permissions.Courses.Read,
    Permissions.CoursePlans.Read,
    Permissions.Grades.Read,
    Permissions.Assessments.Read,
    Permissions.Evaluations.Read, Permissions.Evaluations.Submit,
    Permissions.Reports.Read,
    Permissions.Teacher.Dashboard,
    Permissions.Recommendations.Respond,
    Permissions.Careers.Read, Permissions.Universities.Read,
    Permissions.Profile.Read, Permissions.Profile.Write,
  ],
  student: [
    Permissions.Students.Read, Permissions.Students.Write,
    Permissions.Courses.Read,
    Permissions.CoursePlans.Read, Permissions.CoursePlans.Write,
    Permissions.Grades.Read,
    Permissions.Assessments.Take, Permissions.Assessments.Read,
    Permissions.Evaluations.Read,
    Permissions.Reports.Read,
    Permissions.Coaching.Book,
    Permissions.Careers.Read, Permissions.Universities.Read,
    Permissions.Resume.Manage, Permissions.Portfolio.Manage, Permissions.Learning.Access,
    Permissions.Profile.Read, Permissions.Profile.Write,
    Permissions.Subscriptions.Read,
  ],
  coach: [
    Permissions.Students.Read,
    Permissions.Coaching.Dashboard, Permissions.Coaching.Sessions,
    Permissions.Coaching.Earnings, Permissions.Coaching.Profile,
    Permissions.Profile.Read, Permissions.Profile.Write,
  ],
  parent: [
    Permissions.Students.Read,
    Permissions.Courses.Read,
    Permissions.CoursePlans.Read,
    Permissions.Grades.Read,
    Permissions.Assessments.Read,
    Permissions.Evaluations.Read, Permissions.Evaluations.Submit,
    Permissions.Reports.Read,
    Permissions.Counselor.SessionRequest,
    Permissions.Parent.Dashboard, Permissions.Parent.Children,
    Permissions.Careers.Read, Permissions.Universities.Read,
    Permissions.Profile.Read, Permissions.Profile.Write,
  ],
};
