using System.Reflection;
using System.Text.Json;
using FormMaps.Application.CareerFit;
using Xunit.Abstractions;

namespace FormMaps.UnitTests.CareerFit;

/// <summary>
/// FM-CF-004 parity: the embedded rule set, resolved per scorable family exactly like
/// tools/careerfit/mc_lib.py resolved_bundle(), run through EvaluateOwner for every fixture case, must
/// reproduce what the NORMATIVE docs/careerfit/sources/formmaps_engine_reference.py produced for the same
/// inputs (CareerFit/Data/parity-fixture.json, 60 cases x 14 families, generated by
/// tools/careerfit/export_parity_fixture.py). Every numeric field within 1e-9, every string field equal.
/// The fixture carries the spec's single convergence pair (70/55) because the reference has only that,
/// so the rule set's per_instrument recut is stripped here (it is exercised by the boundary tests).
/// If anything diverges the C# is wrong, not the fixture.
/// </summary>
public class CareerFitParityTests(ITestOutputHelper output)
{
    private const double Tolerance = 1e-9;

    private static readonly string[] NumericFields =
        ["pca_route_fit", "competency_fit", "pca_index", "mil_fit", "personality_fit", "careerfit360", "careerfit_absolute"];

    private static readonly string[] StringFields =
        ["pca_winning_route", "competency_gate", "mil_gate", "personality_winning_route", "final_gate", "convergence_level"];

    private static readonly JsonElement Fixture = LoadFixture();

    private static JsonElement LoadFixture()
    {
        var assembly = Assembly.GetExecutingAssembly();
        var name = assembly.GetManifestResourceNames().Single(n => n.EndsWith("parity-fixture.json", StringComparison.Ordinal));
        using var stream = assembly.GetManifestResourceStream(name)!;
        return JsonDocument.Parse(stream).RootElement.Clone();
    }

    [Fact]
    public void Fixture_pins_the_embedded_rule_set_version_weights_and_tolerance()
    {
        var rules = CareerFitRulesJson.LoadEmbedded(Fixture.GetProperty("rules_version").GetString()!);
        Assert.Equal(Fixture.GetProperty("rules_version").GetString(), rules.RulesVersion);
        Assert.Equal(Tolerance, Fixture.GetProperty("tolerance").GetDouble());

        // The fixture was scored with the rule set's own weights; a drift here means a stale fixture.
        var w = Fixture.GetProperty("weights");
        Assert.Equal(w.GetProperty("career_fit").GetProperty("MIL").GetDouble(), rules.Weights.CareerFit.Mil);
        Assert.Equal(w.GetProperty("career_fit").GetProperty("PCA").GetDouble(), rules.Weights.CareerFit.Pca);
        Assert.Equal(w.GetProperty("career_fit").GetProperty("PERSONALITY").GetDouble(), rules.Weights.CareerFit.Personality);
        Assert.Equal(w.GetProperty("career_fit").GetProperty("VOCATIONAL_360").GetDouble(), rules.Weights.CareerFit.Vocational360);
        Assert.Equal(w.GetProperty("pca_internal").GetProperty("DISC").GetDouble(), rules.Weights.PcaInternal.Disc);
        Assert.Equal(w.GetProperty("pca_internal").GetProperty("COMPETENCIES").GetDouble(), rules.Weights.PcaInternal.Competencies);

        // The reference hard-codes these role weights; the rule set must carry the same numbers for the
        // config-driven port to be the same engine.
        Assert.Equal(3.0, rules.Weights.CompetencyRole["CRITICAL"]);
        Assert.Equal(2.0, rules.Weights.CompetencyRole["IMPORTANT"]);
        Assert.Equal(3.0, rules.Weights.MilRole["CRITICAL"]);
        Assert.Equal(2.0, rules.Weights.MilRole["IMPORTANT"]);
        Assert.Equal(1.0, rules.Weights.MilRole["COMPLEMENTARY"]);

        // The fixture's single convergence pair is the spec's (F22/F23) and the rule set's own pair.
        Assert.Equal(70.0, Fixture.GetProperty("thresholds").GetProperty("strong_support_min").GetDouble());
        Assert.Equal(55.0, Fixture.GetProperty("thresholds").GetProperty("partial_support_min").GetDouble());
        Assert.Equal(70.0, rules.Thresholds.Convergence.StrongMin);
        Assert.Equal(55.0, rules.Thresholds.Convergence.PartialMin);
    }

    [Fact]
    public void Every_case_and_family_matches_the_reference_engine()
    {
        var rules = CareerFitRulesJson.LoadEmbedded(Fixture.GetProperty("rules_version").GetString()!);
        var thresholds = ReferenceThresholds(rules);
        var bundles = rules.ScorableFamilies
            .ToDictionary(f => f.FamilyId.ToString(), f => ResolvedFamilyRules.FromFamily(rules, f), StringComparer.Ordinal);
        Assert.Equal(14, bundles.Count);

        var cases = 0;
        var comparisons = 0;
        var maxDeviation = 0.0;
        var maxDeviationAt = "(none)";
        var failures = new List<string>();

        foreach (var c in Fixture.GetProperty("cases").EnumerateArray())
        {
            cases++;
            var caseId = c.GetProperty("case_id").GetInt32();
            var assessment = ReadAssessment(c.GetProperty("inputs"));
            var familiesSeen = 0;
            foreach (var expected in c.GetProperty("expected_by_family").EnumerateObject())
            {
                familiesSeen++;
                var bundle = bundles[expected.Name];
                var actual = CareerFitFormulas.EvaluateOwner(assessment, bundle, rules.Weights, thresholds);
                Assert.Equal(ResolvedFamilyRules.FamilyOwnerType, actual.OwnerType);
                Assert.Equal(int.Parse(expected.Name), actual.OwnerId);

                foreach (var field in NumericFields)
                {
                    var want = expected.Value.GetProperty(field).GetDouble();
                    var got = NumericField(actual, field);
                    var deviation = Math.Abs(want - got);
                    comparisons++;
                    if (deviation > maxDeviation || double.IsNaN(deviation))
                    {
                        maxDeviation = deviation;
                        maxDeviationAt = $"case {caseId} family {expected.Name} {field}";
                    }

                    if (!(deviation <= Tolerance))
                    {
                        failures.Add($"case {caseId} family {expected.Name} {field}: expected {want:R} got {got:R} (|d|={deviation:E3})");
                    }
                }

                foreach (var field in StringFields)
                {
                    var want = expected.Value.GetProperty(field).GetString();
                    var got = StringField(actual, field);
                    comparisons++;
                    if (want != got)
                    {
                        failures.Add($"case {caseId} family {expected.Name} {field}: expected {want} got {got}");
                    }
                }
            }

            Assert.Equal(14, familiesSeen);
        }

        output.WriteLine($"CareerFit parity: {cases} cases x 14 families, {comparisons} field comparisons, " +
                         $"max abs deviation {maxDeviation:E3} at {maxDeviationAt}, tolerance {Tolerance:E0}");
        Assert.Equal(60, cases); // guards against the fixture silently emptying
        Assert.True(failures.Count == 0, $"{failures.Count} divergence(s) from the reference engine:\n" + string.Join("\n", failures.Take(25)));
    }

    [Fact]
    public void Every_fixture_case_passes_ValidateInputs()
    {
        // The generator only produces in-range inputs; the port's validation must agree with that.
        foreach (var c in Fixture.GetProperty("cases").EnumerateArray())
        {
            var a = ReadAssessment(c.GetProperty("inputs"));
            CareerFitFormulas.ValidateInputs(a.Pca, a.Competencies, a.Mil, a.Personality);
        }
    }

    [Fact]
    public void Ranking_the_fourteen_families_of_a_case_puts_the_highest_absolute_first()
    {
        var rules = CareerFitRulesJson.LoadEmbedded(Fixture.GetProperty("rules_version").GetString()!);
        var thresholds = ReferenceThresholds(rules);
        var bundles = rules.ScorableFamilies.Select(f => ResolvedFamilyRules.FromFamily(rules, f)).ToList();

        var c = Fixture.GetProperty("cases")[0];
        var assessment = ReadAssessment(c.GetProperty("inputs"));
        var evaluations = bundles.Select(b => CareerFitFormulas.EvaluateOwner(assessment, b, rules.Weights, thresholds)).ToList();

        var ranked = CareerFitFormulas.AssignRelativeFit(evaluations);

        Assert.Equal(14, ranked.Count);
        Assert.Equal(evaluations.Max(e => e.CareerFitAbsolute), ranked[0].CareerFitAbsolute);
        Assert.Equal(1, ranked[0].RankPosition);
        Assert.Equal(100.0, ranked[0].CareerFitRelative);
        Assert.Equal(14, ranked[^1].RankPosition);
        Assert.Equal(0.0, ranked[^1].CareerFitRelative);
        for (var i = 1; i < ranked.Count; i++)
        {
            Assert.True(ranked[i - 1].CareerFitAbsolute >= ranked[i].CareerFitAbsolute);
            Assert.Equal(i + 1, ranked[i].RankPosition);
        }

        Assert.All(evaluations, e => Assert.Null(e.RankPosition)); // inputs untouched
    }

    // The reference's Thresholds() has only the single pair: strip the rule set's per_instrument recut.
    private static CareerFitThresholds ReferenceThresholds(CareerFitRules rules)
    {
        var t = Fixture.GetProperty("thresholds");
        return rules.Thresholds with
        {
            Convergence = new ConvergenceThresholds(
                StrongMin: t.GetProperty("strong_support_min").GetDouble(),
                PartialMin: t.GetProperty("partial_support_min").GetDouble(),
                PerInstrument: null),
        };
    }

    private static CareerFitAssessment ReadAssessment(JsonElement inputs)
    {
        var pca = inputs.GetProperty("pca");
        var mil = inputs.GetProperty("mil");
        var p = inputs.GetProperty("personality");
        var competencies = inputs.GetProperty("competencies").EnumerateObject()
            .ToDictionary(kv => int.Parse(kv.Name), kv => kv.Value.GetInt32());
        var v360 = new Dictionary<string, V360Aggregate>(StringComparer.Ordinal);
        foreach (var v in inputs.GetProperty("v360").EnumerateObject())
        {
            v360[v.Name] = new V360Aggregate(v.Value.GetDouble());
        }

        return new CareerFitAssessment(
            Pca: new PcaInput(pca.GetProperty("D").GetDouble(), pca.GetProperty("I").GetDouble(), pca.GetProperty("S").GetDouble(), pca.GetProperty("C").GetDouble()),
            Competencies: competencies,
            Mil: new MilInput(mil.GetProperty("DC").GetInt32(), mil.GetProperty("RZ").GetInt32(), mil.GetProperty("VN").GetInt32(), mil.GetProperty("MT").GetInt32(), mil.GetProperty("OR").GetInt32()),
            Personality: new PersonalityInput(
                p.GetProperty("E").GetDouble(), p.GetProperty("I").GetDouble(), p.GetProperty("S").GetDouble(), p.GetProperty("N").GetDouble(),
                p.GetProperty("T").GetDouble(), p.GetProperty("F").GetDouble(), p.GetProperty("J").GetDouble(), p.GetProperty("P").GetDouble()),
            V360Aggregates: v360,
            CareerFit360Confidence: CareerFitEnums.ParseConfidence(inputs.GetProperty("careerfit360_confidence").GetString()!));
    }

    private static double NumericField(OwnerEvaluation e, string field) => field switch
    {
        "pca_route_fit" => e.PcaRouteFit,
        "competency_fit" => e.CompetencyFit,
        "pca_index" => e.PcaIndex,
        "mil_fit" => e.MilFit,
        "personality_fit" => e.PersonalityFit,
        "careerfit360" => e.CareerFit360,
        "careerfit_absolute" => e.CareerFitAbsolute,
        _ => throw new ArgumentOutOfRangeException(nameof(field), field, null),
    };

    private static string StringField(OwnerEvaluation e, string field) => field switch
    {
        "pca_winning_route" => e.PcaWinningRoute,
        "competency_gate" => e.CompetencyGate.ToReferenceValue(),
        "mil_gate" => e.MilGate.ToReferenceValue(),
        "personality_winning_route" => e.PersonalityWinningRoute,
        "final_gate" => e.FinalGate.ToReferenceValue(),
        "convergence_level" => e.ConvergenceLevel.ToReferenceValue(),
        _ => throw new ArgumentOutOfRangeException(nameof(field), field, null),
    };
}
